### ISSUE TITLE
Resolve issues with autocomplete service used by AODN in cluster

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#349]
Resolve the remaining issues with the cluster name autocomplete

**Comment by ansell** [comment]
Regressions reported by AODN include:

- [ ] https://github.com/AtlasOfLivingAustralia/biocache-service/issues/203 Intermittent failures for autocomplete search
- [ ] https://github.com/AtlasOfLivingAustralia/biocache-service/issues/218 OGC getFeatureInfo not working
- [x] https://github.com/AtlasOfLivingAustralia/biocache-service/issues/252 species_habitats field missing. Fixed by running jenkins job to populate species_habitats field. Adding check to the solr collection swap jenkins job to verify that species_habitats will be populated in future

A feature request by AODN is:

- [ ] https://github.com/AtlasOfLivingAustralia/biocache-service/issues/315
