### ISSUE TITLE
Cleanup duplicated records due to biocache store DwCA key issue

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#379]
The following data resources need to be evaluated to determine the number of duplicated records that have been loaded into cassandra and/or indexed in solr due to https://github.com/AtlasOfLivingAustralia/biocache-store/issues/282

Anomalous key count | Data resource UID
---------------------- | ------------------
14962 | dr2287
430906 | dr341
49865 | dr342
404323 | dr376
5403 | dr4218
242 | dr7965
92 | dr8216
27968 | dr836

The command used to generate the list above was:

```
grep '|Some(' /data/tmp/export.csv_merged | cut -d , -f 1 | cut -d \" -f 2 | cut -d "|" -f 1 | sort | uniq -c
```

- [x] Identify records with keys containing the Scala artifacts.

Some of the data resources above were fixed yesterday, but the entries in the ``occ_uuid`` columnfamily in cassandra remain.

### Bulk removal of records

- [x] Remove all records containing ``|Some(`` in their key. Done... ``aws-bstore-1b 2018-10-03 16:01:14,106 INFO : [RecordDeletor] - Records deleted from index : 933761``

### Data resources affected that need reloading

- [x]  dr2287 - BRI AVH data https://github.com/AtlasOfLivingAustralia/data-management/issues/378 The biocache-store reported loaded record count for this was 533541. If this doesn't match during verification there may have been other issues.
- [x]  dr341 - Australian National Wildlife Collection https://github.com/AtlasOfLivingAustralia/data-management/issues/361
- [x]  dr342 - Museums Victoria provider for OZCAM https://github.com/AtlasOfLivingAustralia/data-management/issues/380
- [x]  dr376 - MEL AVH data https://github.com/AtlasOfLivingAustralia/data-management/issues/381
- [x]  dr4218 - School of Ants https://github.com/AtlasOfLivingAustralia/data-management/issues/374
- [x]  dr7965 - Dirk Hartog Island Birds https://github.com/AtlasOfLivingAustralia/data-management/issues/382
- [x]  dr8216 - Surveys of Orpheus Island by James Cook University staff and students https://github.com/AtlasOfLivingAustralia/data-management/issues/383
- [x]  dr836 -  Lizard Island Research Station https://github.com/AtlasOfLivingAustralia/data-management/issues/367

### Data resources affected that need verifying

- [ ]  dr2287 - BRI AVH data https://github.com/AtlasOfLivingAustralia/data-management/issues/378 solr is reporting 533,917 records, which is slightly more and needs removal of data records that were not duplicated, but were removed in the latest copy. Waiting on https://github.com/AtlasOfLivingAustralia/biocache-store/issues/285 to cleanup records that were deleted by the data provider since the previous data was delivered.
- [x]  dr341 - Australian National Wildlife Collection https://github.com/AtlasOfLivingAustralia/data-management/issues/361
- [ ]  dr342 - Museums Victoria provider for OZCAM https://github.com/AtlasOfLivingAustralia/data-management/issues/380 (Verifying the record count is not possible due to the load coming from a delta)
- [ ]  dr376 - MEL AVH data https://github.com/AtlasOfLivingAustralia/data-management/issues/381 (Verifying the record count is not possible due to the load coming from a delta)
- [x]  dr4218 - School of Ants https://github.com/AtlasOfLivingAustralia/data-management/issues/374
- [x]  dr7965 - Dirk Hartog Island Birds https://github.com/AtlasOfLivingAustralia/data-management/issues/382
- [x]  dr8216 - Surveys of Orpheus Island by James Cook University staff and students https://github.com/AtlasOfLivingAustralia/data-management/issues/383
- [x]  dr836 -  Lizard Island Research Station https://github.com/AtlasOfLivingAustralia/data-management/issues/367
