### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#407]
- [x] Investigate whether application attribute on apikeys is used, and if so, what is its designed purpose https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/47
- [ ] Specieslists support for apikeys for rate limiting https://github.com/AtlasOfLivingAustralia/specieslist-webapp/issues/95
- [ ] Identify current apikeys and deactivate old apikeys https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/48
- [ ] Add authorisation levels to apikeys https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/46
- [ ] Require authentication of apikey for scheduleArtifactGeneration https://github.com/AtlasOfLivingAustralia/image-service/issues/41
- [ ] Security flaw in collectory api, all fields are public https://github.com/AtlasOfLivingAustralia/collectory-plugin/issues/104
- [ ] Require apikeys for online downloads https://github.com/AtlasOfLivingAustralia/biocache-service/issues/326
- [ ] Make email address a mandatory parameter for /ws/occurrences/index/download https://github.com/AtlasOfLivingAustralia/biocache-service/issues/343
- [ ] Support apikeys for /alaAdmin/ operations so they can be scripted https://github.com/AtlasOfLivingAustralia/ala-hub/issues/29
- [ ] Remove non-Atlas-Of-Living-Australia applications from https://auth.ala.org.au/apikey/ https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/49
- [x] Add review and revocation interface by application, user, last used data https://github.com/AtlasOfLivingAustralia/apikey/issues/5
- [ ] Replace Logger Authorised Systems List with a token/apikey method https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/45
- [ ] Replace CAS Authorised Systems List with a token/apikey method https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/44
- [ ] Biocache-service apikey cache is permanent https://github.com/AtlasOfLivingAustralia/biocache-service/issues/374
- [ ] Prevent apiKey param from being displayed in error messages https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/247
- [ ] Consistent API key authentication https://github.com/AtlasOfLivingAustralia/collectory-plugin/issues/35

**Comment by vjrj** [comment]
I'm trying to document the ALA API keys here:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/API-Keys
comments and edits welcome.
