### ISSUE TITLE
Image management

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#408]
image storage (migrate to S3 object storage?)
image load - retrieving images from cloudstor etc
image selection and display on species pages 
image display on galleries
image flagging and sorting
HISCOM image issues list

3D image loading (Which formats are users providing 3D images in and can we standardise on one during loading)
3D image thumbnails (Animated GIF)
3D image viewing (WebGL?)

Remove pre-generated background thumbnails https://github.com/AtlasOfLivingAustralia/image-service/issues/67 (Possibly not a large amount of storage improvement for this, but would be good to switch to PNG+Alpha channels to avoid having to pre-generate backgrounds)

Duplicate images issue list:

- [ ] AtlasOfLivingAustralia/data-management#346
- [ ] AtlasOfLivingAustralia/biocache-store#271
- [ ] AtlasOfLivingAustralia/biocache-store#164
- [ ] AtlasOfLivingAustralia/biocache-store#119
- [ ] AtlasOfLivingAustralia/biocache-store#72
- [x] AtlasOfLivingAustralia/image-service#26
- [x] AtlasOfLivingAustralia/image-service#19
- [x] AtlasOfLivingAustralia/image-service#5
- [ ] AtlasOfLivingAustralia/image-service#69
