### ISSUE TITLE
Secure cookie and HSTS preload

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#414]
This is a security related epic to describe the process of getting to the point where we can confidently tell browsers to ``HSTS preload`` the entire `ala.org.au` and its subdomains. 

The current situation is:

- [x] ALA systems all support HTTPS (some such as logger.ala.org.au still have HTTP directly responding for compatibility with old hardcoded URLs)
- [x] HSTS is set for each of the ala servers with just a `maxage`
- [x] The `TGC` cookie used solely on `auth.ala.org.au/cas/` to authenticate users is marked as `Secure`
- [ ] The `ALA-Auth` cookie set by `auth.ala.org.au` on `ala.org.au` is not marked as `Secure`. However, it doesn't seem to be cryptographically important, so it is a lower priority than the app specific cookies. https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/59
- [ ] The `JSESSIONID` cookies set by each subdomain are not consistently marked as `Secure`. These need to be secure, as they are cryptographically important because they are the marker into the server session store.
- [ ] Development on developers local machines shouldn't need to be available in HTTPS, as they are used locally rather than over the internet. To enable this, we would need to create a new domain for test and development systems https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/57
- [ ] After there is a dedicated domain and an instance of CAS for developers to use, the next goal is to switch development systems from ``*.ala.org.au`` to the new domain. This ensures that the development systems can continue to run on local developer PCs without them installing a TLS certificate locally. ``devt.ala.org.au`` will need to be swtiched to the new top level domain  https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/58
- [x] Add known certificate authority list to the ALA DNS record to prevent creation of certificates by other CA's. However, this requires the CAA list to include `LetsEncrypt` because it is used by  StatusCake for `status.ala.org.au` https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/43
- [ ] Create a list of supported browsers and other HTTP user-agents https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/60
- [ ] Verify that supported HTTP user-agents/browsers function correctly with Secure `JSESSIONID` cookies https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/61
- [ ] Increase the current HSTS ``max-age`` from 1 year ``max-age=31536000`` to 2 years ``max-age=63072000`` https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/62
- [ ] Configure the ALA HSTS setting in nginx configurations to ``include subdomains`` https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/63
- [ ] Configure the ALA HSTS setting in nginx configurations to include``preload`` https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/64
- [ ] Submit ``ala.org.au`` to browsers for preload https://hstspreload.org/ https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/65
