### ISSUE TITLE
Caching fixes

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#455]
Caching has the potential to reduce underlying resource costs, which is a high-priority for the ALA.

However, the existing nginx caching needs to be switched off until application developers are assigned to fix applications to return HTTP headers that nginx can recognise to know whether it can be correctly cached.

This is an epic for tracking bugs relating to that process which need to be fixed before nginx caching can be switched on again.

- [ ] Biocache-service returns HTTP 200 for error pages https://github.com/AtlasOfLivingAustralia/biocache-service/issues/161
- [ ] Add HTTP Cache headers to biocache occurrence search https://github.com/AtlasOfLivingAustralia/biocache-service/issues/239
- [ ] HTTP 200 returned when an error occurred for bie https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/155
