### ISSUE TITLE
Converting DwC CSV to DwCA

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#709]
- [ ] #749
- [ ] #747
- [ ] Consider dwc terms : refer #714 
- [ ] Determine when the job should fail (if the checks should be implemented in DWCA class #716)
- [ ] #748
- [ ]  Output PROV results: refer #715
