### ISSUE TITLE
Prep for cluster shutdown

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#884]
To shutdown cluster:
- [x] Backup `/var/lib/jenkins/` dir to /data/dmgt efs volume 
- [x] Backup jupyter notebooks on spark-quoll-2 to /data/dmgt efs volume
- [x] Request that /data/dmgt (efs volume) be mounted to uploads

To close off this issue
- [x] request devops shut down (and later terminate) the spark-quoll cluster
- [x] #895

Issues that need addressing:
- [x] Assertions sync needs to be run manually when doing a manual index switch - run it even if the index fails. Patricia to fix index job ( #888 and #889 )
- [x] how to delete a data resource - was a useful thing for deleting data resources (#890 )
- [x] Migrating prod data dwca/uuid to databox #891
- [x] NZ AVH needs a fetcher #892
- [x] QM - dr344 fetcher test in databox, needs to be scheduled
- [x] APII schedule should be running weekly 
- [x] cPlatypus should be scheduled weekly
- [x] #903

**Comment by sadeghim** [comment]
Spark Quoll Cluster is shutdown 18th May, outstanding issues raised. Closing this ticket.
