### ISSUE TITLE
Collections release testing

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#930]
Testing for Release 3.2.0 
https://github.com/AtlasOfLivingAustralia/collectory/releases/tag/3.2.0

Review changes:

- [ ] [Add events and publications resourceTypes #195](https://github.com/AtlasOfLivingAustralia/collectory/issues/195)
- [ ] [Latitude/longitude editing issues caused by localization #188](https://github.com/AtlasOfLivingAustralia/collectory/issues/188)
- [ ] [dataResource.isPrivate field not respected in a number of services #194](https://github.com/AtlasOfLivingAustralia/collectory/issues/194)
- [ ] [Add lastUpdate and num of records to datasets page #183](https://github.com/AtlasOfLivingAustralia/collectory/pull/183)

**Comment by peggynewman** [comment]
Events and Publication resourceTypes:

Firstly, suggest that we update the other resource types in prod, opened ticket for this https://github.com/AtlasOfLivingAustralia/data-management/issues/931

Events resourceType in prod doesn't look good, but looks ok in test:
https://collections.ala.org.au/datasets#filters=resourceType%3Aevents
Note [dataset.result.events]

<img width="979" alt="image" src="https://github.com/AtlasOfLivingAustralia/data-management/assets/1271932/ed7e1791-6c0c-4c0f-9f9b-59e7c960947a">

- appears in picklist Ok when editing/creating DR

**Comment by djtfmartin** [comment]
There is no need to tie this work to #931 - this can be as a separate exercise and it only requires database updates and config changes.

**Comment by peggynewman** [comment]
Totally agree

**Comment by peggynewman** [comment]
I don't see a need to test the localisation problem for ALA

**Comment by peggynewman** [comment]
The .isPrivate field doesn't seem to be fixed: just tested with https://collections-test.ala.org.au/public/showDataResource/dr20239
- still appearing in
- https://collections-test.ala.org.au/datasets
- https://collections-test.ala.org.au/dataResource/list
- but rendering properly : https://collections-test.ala.org.au/public/showDataResource/dr20239

**Comment by djtfmartin** [comment]
@peggynewman can you verify the above is ok ?

**Comment by peggynewman** [comment]
Yes, the private flag now works, and the date and record count works nicely, thanks

**Comment by djtfmartin** [comment]
done
